name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at tag
        uses: actions/checkout@v6.0.2
        
      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./custom_components/sprinkle/frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./custom_components/sprinkle/frontend
        run: npm run build

      - name: Create build folder
        run: |
          mkdir -p .github/build/sprinkle

          cp -r ./custom_components/sprinkle/* .github/build/sprinkle/

          rm -rf .github/build/sprinkle/frontend/*
          
          mkdir -p .github/build/sprinkle/frontend/dist

          cp ./custom_components/sprinkle/frontend/dist/sprinkle-panel.js .github/build/sprinkle/frontend/dist/

      - name: Create Release
        run: |
          mkdir -p release/
          cp -r .github/build/sprinkle release/

      - name: Package project for release
        run: |
          cd release/
          zip -r ./sprinkle.zip .

      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./release/alarmo.zip application/zip